
version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - nodeapp
  nodeapp:
    build: './'
    container_name: hello
    environment:
      - NODE_ENV=production
